//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3625.
// 
#pragma warning disable 1591

namespace Leaflet.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSPrincipalSoap", Namespace="http://tempuri.org/")]
    public partial class WSPrincipal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback novoCadastroOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarcaPontoPersistenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback NovoMapaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregaInformacoesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSPrincipal() {
            this.Url = global::Leaflet.Properties.Settings.Default.Leaflet_localhost_WSPrincipal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event novoCadastroCompletedEventHandler novoCadastroCompleted;
        
        /// <remarks/>
        public event MarcaPontoPersistenciaCompletedEventHandler MarcaPontoPersistenciaCompleted;
        
        /// <remarks/>
        public event NovoMapaCompletedEventHandler NovoMapaCompleted;
        
        /// <remarks/>
        public event CarregaInformacoesCompletedEventHandler CarregaInformacoesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/novoCadastro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string novoCadastro(string email, string senha, string rptSenha) {
            object[] results = this.Invoke("novoCadastro", new object[] {
                        email,
                        senha,
                        rptSenha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void novoCadastroAsync(string email, string senha, string rptSenha) {
            this.novoCadastroAsync(email, senha, rptSenha, null);
        }
        
        /// <remarks/>
        public void novoCadastroAsync(string email, string senha, string rptSenha, object userState) {
            if ((this.novoCadastroOperationCompleted == null)) {
                this.novoCadastroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnovoCadastroOperationCompleted);
            }
            this.InvokeAsync("novoCadastro", new object[] {
                        email,
                        senha,
                        rptSenha}, this.novoCadastroOperationCompleted, userState);
        }
        
        private void OnnovoCadastroOperationCompleted(object arg) {
            if ((this.novoCadastroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.novoCadastroCompleted(this, new novoCadastroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarcaPontoPersistencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MarcaPontoPersistencia(string lat, string lng, string texto, string id_mapa) {
            object[] results = this.Invoke("MarcaPontoPersistencia", new object[] {
                        lat,
                        lng,
                        texto,
                        id_mapa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MarcaPontoPersistenciaAsync(string lat, string lng, string texto, string id_mapa) {
            this.MarcaPontoPersistenciaAsync(lat, lng, texto, id_mapa, null);
        }
        
        /// <remarks/>
        public void MarcaPontoPersistenciaAsync(string lat, string lng, string texto, string id_mapa, object userState) {
            if ((this.MarcaPontoPersistenciaOperationCompleted == null)) {
                this.MarcaPontoPersistenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcaPontoPersistenciaOperationCompleted);
            }
            this.InvokeAsync("MarcaPontoPersistencia", new object[] {
                        lat,
                        lng,
                        texto,
                        id_mapa}, this.MarcaPontoPersistenciaOperationCompleted, userState);
        }
        
        private void OnMarcaPontoPersistenciaOperationCompleted(object arg) {
            if ((this.MarcaPontoPersistenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarcaPontoPersistenciaCompleted(this, new MarcaPontoPersistenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NovoMapa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NovoMapa(string nome_mapa) {
            object[] results = this.Invoke("NovoMapa", new object[] {
                        nome_mapa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NovoMapaAsync(string nome_mapa) {
            this.NovoMapaAsync(nome_mapa, null);
        }
        
        /// <remarks/>
        public void NovoMapaAsync(string nome_mapa, object userState) {
            if ((this.NovoMapaOperationCompleted == null)) {
                this.NovoMapaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNovoMapaOperationCompleted);
            }
            this.InvokeAsync("NovoMapa", new object[] {
                        nome_mapa}, this.NovoMapaOperationCompleted, userState);
        }
        
        private void OnNovoMapaOperationCompleted(object arg) {
            if ((this.NovoMapaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NovoMapaCompleted(this, new NovoMapaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CarregaInformacoes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ponto[] CarregaInformacoes() {
            object[] results = this.Invoke("CarregaInformacoes", new object[0]);
            return ((Ponto[])(results[0]));
        }
        
        /// <remarks/>
        public void CarregaInformacoesAsync() {
            this.CarregaInformacoesAsync(null);
        }
        
        /// <remarks/>
        public void CarregaInformacoesAsync(object userState) {
            if ((this.CarregaInformacoesOperationCompleted == null)) {
                this.CarregaInformacoesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregaInformacoesOperationCompleted);
            }
            this.InvokeAsync("CarregaInformacoes", new object[0], this.CarregaInformacoesOperationCompleted, userState);
        }
        
        private void OnCarregaInformacoesOperationCompleted(object arg) {
            if ((this.CarregaInformacoesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregaInformacoesCompleted(this, new CarregaInformacoesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ponto {
        
        private int id_pontoField;
        
        private string nomeField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string textoField;
        
        private int id_tipo_mapaField;
        
        /// <remarks/>
        public int id_ponto {
            get {
                return this.id_pontoField;
            }
            set {
                this.id_pontoField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
            }
        }
        
        /// <remarks/>
        public int id_tipo_mapa {
            get {
                return this.id_tipo_mapaField;
            }
            set {
                this.id_tipo_mapaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void novoCadastroCompletedEventHandler(object sender, novoCadastroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class novoCadastroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal novoCadastroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void MarcaPontoPersistenciaCompletedEventHandler(object sender, MarcaPontoPersistenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarcaPontoPersistenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarcaPontoPersistenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void NovoMapaCompletedEventHandler(object sender, NovoMapaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NovoMapaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NovoMapaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CarregaInformacoesCompletedEventHandler(object sender, CarregaInformacoesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregaInformacoesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregaInformacoesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ponto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ponto[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591